### ISSUE TITLE
Examples for bridges 

### ISSUE THREAD

**Issue by hvisage** [dresden-weekly/ansible-network-interfaces#1]
Hi there,

 Some examples/documentation for bridges would be appreciated.

 Also, do your rolesremove/replace the original eg. eth0 entries in /etc/network/interfaces when you define an eth0 using this role?

**Comment by arBmind** [comment]
Hi hvisage,

so far I had no use case for bridges.
The defaults/main.yml contains all the available options and defaults.
If you have a use case, I would be more than happy to make an example out of it.

Yes my role creates a new /etc/network/interfaces that includes a configuration file for each device. That should make it much easier to manage the individual network devices.

**Comment by starkers** [comment]
Just thinking out loud here but that shouldn't be too hard to add.

## step one
- add the `bridge-ports` key to  the `device.j2` with (line 6)

## step two
- ensure bridging utils are installed:
  `apt: pkg=bridge-utils state=present`

## step three
- use a config something like this maybe?

```
network_interfaces:

- device: eth0
  description: bridge 1, NIC A
  auto: true
  family: inet
  method: manual

- device: eth1
  description: bridge 1, NIC B
  auto: true
  family: inet
  method: manual

- device: br0
  description: bridge 1
  auto: true
  method: dhcp
  bridge_ports: "eth0 eth1"
```

I'm guessing that would result in something like this hopefully:

```
 iface eth0 inet manual
 iface eth1 inet manual

 iface br0 inet dhcp
  bridge_ports eth0 eth1
```
