### ISSUE TITLE
Respect iproute2 method for multiple IPs

### ISSUE THREAD

**Issue by lieutdan13** [dresden-weekly/ansible-network-interfaces#12]
According to the [Network Configuration for Debian](https://wiki.debian.org/NetworkConfiguration#iproute2_method) documentation, you can have multiple IPs assigned to the same interface name without using virtual or aliased interface names. The file name for devices is as follows `device-{{ item.device }}-{{ item.family | default('inet') }}`, which is not unique if you use this method of multiple IPs.

For example:

```
auto eth0
allow-hotplug eth0
iface eth0 inet static
    address 192.168.1.42
    netmask 255.255.255.0
    gateway 192.168.1.1

iface eth0 inet static
    address 192.168.1.43
    netmask 255.255.255.0

iface eth0 inet static
    address 192.168.1.44
    netmask 255.255.255.0
```

You could have an optional unique identifier to append to the config filenames.
i.e.

```
network_interfaces:
- id: '42'
  device: eth0
  auto: true
  family: inet
  method: static
  address: 192.168.1.42
  ...
- id: '43'
  device: eth0
  auto: true
  family: inet
  method: static
  address: 192.168.1.43
  ...
```

then
`device-{{ item.device }}-{{ item.family | default('inet') }}{{ '-' + item.id if item.id | default('') else '' }}` for the file name.
