### ISSUE TITLE
please make networking restart optional

### ISSUE THREAD

**Issue by gfa** [dresden-weekly/ansible-network-interfaces#3]
hello, thanks for your module
I can tell it works fine on debian jessie :+1:
please make optional the network service restart as it cut all my other interfaces even when `network_manage_devices: no` is configured

**Comment by arBmind** [comment]
Hey, I am pleased that you like this little module.
If we suppress the network service restart how do we get the configuration changes into effect?
Thinking a bit about it, it seems very rude to restart the service - but we could not figure out a better way so far.

**Comment by gfa** [comment]
in my playbook i manually start the interfaces

```
  roles:
    - role: dresden-weekly.network-interfaces
      network_manage_devices: no #if yes all other interfaces are deleted
      network_interfaces:

       - device: eth1
         auto: true
         family: inet
         method: manual
         pre-up: [ifconfig eth1 up]

       - device: eth2
         auto: true
         family: inet
         method: manual
         pre-up: [ifconfig eth2 up]

  tasks:
    # start the nics
    - command: '/sbin/ifup eth1'
    - command: '/sbin/ifup eth2'
```

you can do the same in the module
