### ISSUE TITLE
tunnel interface support

### ISSUE THREAD

**Issue by nnovikov** [dresden-weekly/ansible-network-interfaces#50]
Do you have tunnel interfaces support?

**Comment by dekhtyarev** [comment]
work fine with some config:
```
network_interfaces:
  - id: tunl0-1
    device: tunl0
    description: Tunnel IP
    auto: true
    family: inet
    method: static
    address: 10.XXX.Y.Z1
    netmask: 255.255.255.255

  - id: tunl0-2
    device: tunl0
    description: Tunnel IP
    auto: true
    family: inet
    method: static
    address: 10.XXX.Y.Z2
    netmask: 255.255.255.255

  - device: "{{ ansible_default_ipv4.interface }}"
    description: default interface for OS
    auto: true
    family: inet
    method: dhcp
```
