### ISSUE TITLE
the field 'args' has an invalid value

### ISSUE THREAD

**Issue by dominikkukacka** [dresden-weekly/ansible-network-interfaces#62]
This yml throws an error and I can't really figure out why

```yml
- hosts: server
  remote_user: root
  roles:
    - role: dresden-weekly.network-interfaces
      network_interfaces:
      - device: eth0
        description: private interface
        auto: true
        family: inet
        method: static
        address: 10.0.0.2
        netmask: 255.255.255.192
        allow:
        - hotplug
        post-up:
        - route add -net 10.0.0.0 netmask 255.0.0.0 gw 10.0.0.1
        - route add -net 161.26.0.0 netmask 255.255.0.0 gw 10.0.0.1
```

```bash
fatal: [...]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'dict object' has no attribute 'path'\n\nThe error appears to have been in '/private/etc/ansible/roles/dresden-weekly.network-interfaces/tasks/manage_devices.yml': line 8, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n# depending on change the result stores dest or path\n- name: configured files\n  ^ here\n"}
```

An ideas? Best, Dominik
