### ISSUE TITLE
Can not add virtual interfaces

### ISSUE THREAD

**Issue by dominikkukacka** [dresden-weekly/ansible-network-interfaces#63]
I tried to add a virtual interface to eth1:
```yml
- device: eth1:0
        description: eth1:0 - mydomain.com
        auto: true
        family: inet
        method: static
        address: 1.2.3.4
        netmask: 255.255.255.248
        gateway: 1.2.3.1
        allow:
          - hotplug
```

which resulted in this error:
```bash
dresden-weekly.ansible-network-interfaces : network restart interface command
...
"stderr": "ifdown: interface eth1:0 not configured\nRTNETLINK answers: File exists", 
"stdout": "Failed to bring up eth1:0.",
...
```

The interface file is written but the restart failes.
And yes the interface is already there and up. But should this not work anyway? (It does for eth0/eth1)

**Comment by arBmind** [comment]
This reminds me of the old days, when we used virtual interfaces like that. Today, we just add more IP addresses to a single interface.

What system does still support this old behavior?

**Comment by dominikkukacka** [comment]
This is actually on an Ubuntu 16.04 installation. How do I add multiple IP
addresses with the role?

Am 25.09.2017 19:45 schrieb "Andreas Reischuck" <notifications@github.com>:

**Comment by arBmind** [comment]
Just add them to the routes on `up` and remove them on `down`
```yaml
- device: eth1
  # …
  # add additional IPs
  up:
    - "route add -net 1.2.3.4 netmask 255.255.255.248 gw 1.2.3.1 eth1"
  down:
    - "route delete -net 1.2.3.4 netmask 255.255.255.248 gw 1.2.3.1 eth1"
```
